http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "http://localhost:3000"
          - "http://localhost:8081"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowCredentials: true
        addVaryHeader: true
  routers:
    auth-router:
      rule: "PathPrefix(`/api/auth`)"
      service: auth-service
      entryPoints:
        - web
      middlewares:
        - cors
    restaurant-router:
      rule: "PathPrefix(`/api/customer`)"
      service: restaurant-service
      entryPoints:
        - web
      middlewares:
        - cors
  services:
    auth-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8081
    restaurant-service:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8084
