spring.application.name=restaurant-service
spring.datasource.url=jdbc:postgresql://localhost:5433/goodfood_restaurant
spring.datasource.username=app
spring.datasource.password=appsecret
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
server.port=8084
server.servlet.context-path=/api/restaurant
logging.level.org.springframework.security=DEBUG
logging.level.com.example.authservice=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect